spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/mysql-json-example?useSSL=false&allowPublicKeyRetrieval=true
    username: appUser
    password: appUserPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
      ddl-auto: create-drop
